name: thrid workflow

on: push

jobs:
  run-checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: |
          ls -a
          pwd
      - name: checkout usage
        uses: actions/checkout@v1
      - name: List files after checkout
        run: |
          ls -a
          pwd