name: print greeting messages
on: push
env: 
  greet: PM Modi

jobs: 
  greet-everyone:
    runs-on: ubuntu-latest
    env:
      greet: Irani
    steps:
      - name: greet job
        if: ${{env.greet == 'Irani'}}
        run: echo "Good Morning $greet"
      - name: greet job another
        run: echo "$greet"
        env:
          greet: Amit Shah