name: print greeting messages
on: push

jobs:
  use-predefined-git-variables:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          ls -a
          pwd
          echo "${{GITHUB_SHA}}"
          echo "${{GITHUB_JOB}}"
          echo "${{GITHUB_REPOSITORY}}"
          echo "${{GITHUB_WORKSPACE}}"