name: First Workflow

on: push

jobs:
  create-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo  "Hello World"
      - name: run a python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  
  create-second-job:
    runs-on: windows-latest
    steps:
      - name: Directory Bash
        run: pwd
        shell: bash
        